<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>StudentCenter.ApiGateway</AssemblyName>
    <RootNamespace>StudentCenter.ApiGateway</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>
</Project>
