<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>StudentCenter.FoodService</AssemblyName>
    <RootNamespace>StudentCenter.FoodService</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BuildingBlocks/Messaging/Messaging.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../BuildingBlocks/Security/AccountAccessValidation.cs" Link="Infrastructure/Security/AccountAccessValidation.cs" />
  </ItemGroup>
</Project>
